name: trigger - Build all

on: [push, pull_request]

jobs:
  build:

    steps:
      runs-on: ubuntu-latest

    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Run 'build-all'
      uses: ./.github/workflows/build-all
